behaviorPackSource: ./behavior_packs/peanut_example
resourcePackSource: ./resource_packs/peanut_example
behaviorPackTarget: ...\development_behavior_packs\peanut_example
resourcePackTarget: ...\development_resource_packs\peanut_example
